### PR TITLE
feat: bump ns and context to v1

### LINKED ISSUE #130: Bump context and namespace URI to v1
### What's missing?

Following the discussion about release https://github.com/eclipse-dataspace-dcp/decentralized-claims-protocol/discussions/128 the following changes are required in order to support 

context uri: https://w3id.org/dspace-dcp/v1.0/dcp.jsonld
namespace uri: https://w3id.org/dspace-dcp/v1.0/

- [ ] changes in artifacts
- [ ] changes in perma-id dspace-dcp 

### Why should it be in the spec?

Relase preparation

### Where should this be added?

_No response_

### More context

_No response_

### PR DESCRIPTION
**Pull request by wolf4ood**
## WHAT

 bump ns and context to v1

Closes  #130

### CODE REVIEW

**Comment by arnoweiss** [comment]
If we merge this as-is, the redirects will point to a 0.8 URL that will serve 1.0 files. This isn't ideal but we'll have to adjust the redirects anyway due to #123. I'll open another ticket for this.

**Review by arnoweiss — APPROVED** [review]

**Comment by wolf4ood** [comment]
Oh i actually forgot to change the deploy stuff, we need to do change it before merge it.
I will then proceed to change the perma id with the v1 redirect. is that ok?

**Comment by arnoweiss** [comment]
If we merge now, the 0.8 files aren't going to resolve at all, I think. I'm working on a PR that publishes spec text and artifacts for all releases (0.8.0, 0.8.1, HEAD). The path pattern will be:
- `https://eclipse-dataspace-dcp.github.io/decentralized-claims-protocol/releases/HEAD/resources/`
- `https://eclipse-dataspace-dcp.github.io/decentralized-claims-protocol/releases/0.8.0/resources/`
- `https://eclipse-dataspace-dcp.github.io/decentralized-claims-protocol/releases/0.8.1/resources/`

currently it's hard-coded as resources/0.8. If you wanna prepare a PR for that on w3id, that's fine. 

I think a short timeframe of non-resolution is inevitable as this, my subsequent PR and the redirects will not be merged in sync.

edit: idea scrapped as requested differently in #123

**Review by jimmarino — APPROVED** [review]

**Comment by jimmarino** [comment]
@arnoweiss can you handle the merging of this PR and the others you refer to when you are ready?

**Comment by wolf4ood** [comment]
I think it's fine though the artifacts were not there for 0.8 release and they basically refer to the 1.0 version right?

**Pull request merged**
