### PR TITLE
fix missing presentation def in json schema

### LINKED ISSUE #97: `PresentationQueryMessage` is inconsistent between schemas and spec
### What's wrong?

The section [Query for Presentations](https://eclipse-dataspace-dcp.github.io/decentralized-claims-protocol/#query-for-presentations) states that a `PresentationQueryMessage` MUST include EITHER a `scope` or a `presentationDefinition` property. The [schema](https://github.com/eclipse-dataspace-dcp/decentralized-claims-protocol/blob/main/artifacts/src/main/resources/presentation/presentation-query-message-schema.json) in the artifacts folder doesn't reflect this as in only contains `scope` and makes it required.

### Why is this a bug?

It must be consistent. Currently, the schemas are out of sync. 

### How could it be fixed?

There may be a reason to restrict the message to either. The project should decide to ditch either OR adjust the schemas and examples.

### More context

_No response_

### PR DESCRIPTION
**Pull request by wolf4ood**
## WHAT

fix missing presentation def in json schema

Closes #97 

## How was the issue fixed?

_Briefly state why the change was necessary._

## More context

_List other areas that have changed but are not necessarily linked to the main feature. This could be naming changes,
bugs that were encountered and were fixed inline, etc._

### CODE REVIEW

**Review by jimmarino — APPROVED** [review]

**Comment by arnoweiss** [comment]
Does it make sense to define the `presentation` property without defining the `presentation definition` object's structure? This could be tricky because the object is governed outside of DCP. I'd put into question if we need it at all.

**Comment by wolf4ood** [comment]
Unless we want to profile it, probably it worth investigating a schema reference to the presentation definition.

**Review by arnoweiss — APPROVED** [review]
Ok, I'll open another issue for this. Thanks for the initial addition here.

**Pull request merged**
